### ISSUE TITLE
Issues with the 3.5 filter.

### ISSUE THREAD

**Issue by GlenCFL** [Crymsius/Crymsius-filter#4]
This is just a heads up about some potential problems with your filter, as I run most of the FilterBlast ones through my extension just to catch my own errors.

- "Torture Chamber Map" is still under a uniques list. Oba's Cursed Trove is now an Underground Sea map.
- "Gravicius's Veiled" should be "Gravicius' Veiled" going by the item filter post.
- "Fractured Fossil " should be "Fractured Fossil". This actually isn't an error in-game, but it will not catch the Fractured Fossil either.

**Comment by Crymsius** [comment]
Thanks a lot for the heads up ! I'll correct that right now :)

**Comment by Crymsius** [comment]
Hmmm funny enough, the space at the end of fractured fossil is included in the ingame name (and in all the api stuff later on(check https://www.pathofexile.com/trade/search/Standard , or the poe.ninja api). I've just tested it, the highlight works correctly since its full name is "Fractured Fossil " with the space.
I'm pushing fixes for the two other ones. Thanks again :)

**Comment by GlenCFL** [comment]
That's a fix on my end then, so thanks for looking into that.
